---
- hosts: agents
  remote_user: root 
  tasks:
    - name: yum upgrade all packages
      yum:
        name: *
        state: latest
    - name: yum install java, git and net-tools
      yum:
        name:
          - java-1.8.0-openjdk
          - git
          - net-tools
        state: latest
    - name: uninstall old versions
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent
    - name: install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        update_cache: true
    - name: add repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
    - name: install docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: true
