version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
      - /home/jenkins/.ssh:/var/jenkins_home/.ssh
    networks:
      jenkins_net:
        ipv4_address: 172.18.0.22
    restart: unless-stopped
  web:
    image: nginx:latest
    depends_on: 
      - jenkins
    networks:
      jenkins_net:
        ipv4_address: 172.18.0.11
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certs:/var/certs
      - ./proxy_nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

volumes:
  jenkins_data:
networks:
  jenkins_net:
    ipam:
      driver: default
      config:
      - subnet: "172.18.0.0/24"
