version: '3'
services:
  jenkins:
    image: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins_net:
        ipv4_address: 172.18.0.22
    restart: unless-stopped
  web:
    image: nginx:latest
    depends_on: 
      - jenkins
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certs:/var/certs
      - ./jenkins.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

volumes:
  jenkins-data:
networks:
  jenkins_net:
    ipam:
      driver: default
      config:
      - subnet: "172.18.0.0/24"
